services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    container_name: dkkm-web-prod
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dkkm-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60"

  db:
    image: mongo:8.0
    container_name: dkkm-mongo-prod
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${STAGGING_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${STAGGING_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${STAGGING_DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - dkkm-network
    healthcheck:
      test: echo 'db.runCommand({ping:1}).ok' | mongosh db:27017/${STAGGING_DB_NAME} --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"
    restart: unless-stopped


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/share/nginx/html/staticfiles:ro
      - media_volume:/usr/share/nginx/html/media:ro
    container_name: dkkm-nginx-prod
    expose:
      - "80"
    depends_on:
      - web
    networks:
      - dkkm-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: dkkm-cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nginx
    networks:
      - dkkm-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"   

volumes:
  mongo_data: 
  static_volume:
  media_volume:

networks:
  dkkm-network:
    driver: bridge